services:
  - type: web
    name: internnext-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://internnext-backend.onrender.com/api  # Update with your backend URL
