services:
  # Backend Service
  - type: web
    name: internnext-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll set this manually
      - key: CORS_ORIGIN
        value: https://internnext-frontend.onrender.com  # Update with your frontend URL

  # Frontend Service
  - type: web
    name: internnext-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://internnext-backend.onrender.com/api  # Update with your backend URL
