services:
  - type: web
    name: internnext-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: CORS_ORIGIN
        value: https://frontend-vercel-zbmt.onrender.com  # Your actual frontend URL
